Repository Bastion-BaaS/admin-app, pull requests merged in 2022-03, with the labels that each got.

#1 Create baas instance
  controllers/instanceController.js
  index.js
  routes/instanceRouter.js
  utils/bastion-instance-no-comments.yaml
Labels: Ready to merge

#2 add app-server public repo the CF files and rename them
  .gitignore
  controllers/instanceController.js
  index.js
  utils/bastion-development.yaml
  utils/bastion-production.yaml
  utils/test-instance.yaml
Labels: Needs Review

#3 Handle multiple baas instances
  .gitignore
  controllers/instanceController.js
  index.js
  models/httpError.js
  models/instance.js
  models/listenerRulesPriority.js
  package-lock.json
  package.json
  utils/bastion-development.yaml
  utils/bastion-production.yaml
Labels: Qualified Approval

#4 App server communication
  controllers/cloudCodeController.js
  controllers/collectionController.js
  controllers/dataController.js
  controllers/dbController.js
  controllers/instanceController.js
  controllers/userController.js
  index.js
  models/instance.js
  package-lock.json
  package.json
  routes/cloudCodeRouter.js
  routes/collectionRouter.js
  routes/dataRouter.js
  routes/dbRouter.js
  routes/instanceRouter.js
  routes/userRouter.js
  utils/helper.js
  utils/middleware.js
Labels: Reviewing

#8 Build ccf creation functionality
  aws/CCFTemplate.yaml
  aws/bastion-test.zip
  aws/ccf.js
  aws/index.js
  controllers/cloudCodeController.js
  controllers/instanceController.js
  db/index.js
  package-lock.json
  package.json
  routes/cloudCodeRouter.js
  utils/config.js
  utils/helper.js
Labels: Needs Review

#11 Use name parameter on collections routes
  controllers/collectionController.js
  routes/collectionRouter.js
Labels: Needs Review

#12 Use form-data middleware and update ccf module
  aws/ccf.js
  controllers/cloudCodeController.js
  index.js
  package-lock.json
  package.json
  utils/middleware.js
Labels: Ready to Merge

#13 rm hard coded values/files and use async/await only
  aws/bastion-test.zip
  aws/index.js
  controllers/cloudCodeController.js
Labels: Ready to Merge

#14 End to end ccf
  aws/CCFTemplate.yaml
  aws/ccf.js
  controllers/cloudCodeController.js
  index.js
  models/instance.js
  utils/bastion-development.yaml
Labels: Needs Review

#15 Coordinate CLI CF with Admin-App CF
  controllers/instanceController.js
  db/index.js
  docker-compose.yaml
  index.js
  utils/bastion-development.yaml
  utils/bastion-production.yaml
  utils/config.js
  utils/helper.js
Labels: Ready to Merge
