Repository Bastion-BaaS/admin-app, pull requests merged in 2022-04, with the labels that each got.

#16 Deploy DB Server tasks in DB Tier subnet
  utils/bastion-production.yaml
Labels: Ready to Merge

#17 Add session store for admin app login
  controllers/adminController.js
  db/index.js
  docker-compose.yaml
  index.js
  package-lock.json
  package.json
  routes/adminRouter.js
  utils/adminAuth.js
  utils/bastion-development.yaml
  utils/bastion-production.yaml
  utils/config.js
Labels: Needs Review

#18 use *-files and *-ccfs buckets
  aws/ccf.js
  controllers/cloudCodeController.js
  controllers/instanceController.js
  models/instance.js
  utils/bastion-development.yaml
  utils/bastion-production.yaml
  utils/helper.js
Labels: Approved

#21 Auth updates
  aws/CCFTemplate.yaml
  aws/ccf.js
  controllers/adminController.js
  controllers/instanceController.js
  index.js
  utils/adminAuth.js
  utils/bastion-production.yaml
  utils/config.js
Labels: Needs Review

#22 Add tests
  controllers/cloudCodeController.js
  controllers/collectionController.js
  controllers/fileController.js
  controllers/instanceController.js
  controllers/userController.js
  package-lock.json
  package.json
  tests/cloudCode.test.js
  tests/collections.test.js
  tests/files.test.js
  tests/instances.test.js
  tests/users.test.js
Labels: Needs Review
